name = "dissue"
main = "src/worker.ts"
compatibility_date = "2026-08-02"
compatibility_flags = ["nodejs_compat"]
account_id = "9d830dced26757ef120f7f7789534039"

[[kv_namespaces]]
binding = "GUILD_CONFIG"
id = "fc9d82ba152941bfbd84e9cd3126071d"
